name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          set -e
          cmp -s lean-toolchain docs/lean-toolchain
      - uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail"
          mk_all-check: "true"
      - run: |
          set -e
          lake exe shake Cslib
