# taken from https://github.com/leanprover/lean4/blob/114f7e42f1abd10885e91698cd2910b1e4d76083/.github/workflows/pr-title.yml
# the regex is altered to allow parentheses after the type as Mathlib does, e.g. `feat(CI): add workflow to check for commit convention`

name: Check PR title for commit convention

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: actions/github-script@v8
        with:
          script: |
            const msg = context.payload.pull_request? context.payload.pull_request.title : context.payload.merge_group.head_commit.message;
            console.log(`Message: ${msg}`)
            if (!/^(ci|feat|fix|doc|style|refactor|test|chore|perf)(\(.*\))?: .*[^.]($|\n\n)/.test(msg)) {
              core.setFailed('PR title does not follow the Commit Convention (https://leanprover.github.io/lean4/doc/dev/commit_convention.html).');
            }
